# @package _global_
dataset:
  _target_: src.data.ClimateRealDatasetCollection       # Will be dynamically instantiated
  seed: ${exp.seed}
  name: climate_real
  #path: data/processed/climate_data.csv                # Path with Climate dataset (csv)
  path: data/processed/us_data_2013_2022_wspd.csv                # Path with Climate dataset (csv)
  min_seq_length: 30                                   # Min sequence length in cohort
  max_seq_length: 60                                   # Max sequence length in cohort
  #max_number: 300                                     # Maximum number of patients in cohort
  max_number: 300                                     # Maximum number of patients in cohort
  projection_horizon: 5                                # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  split:
    val: 0.15
    test: 0.15
  #val_batch_size: 512                                  # Batch size for evaluation
  val_batch_size: 32                                  # Batch size for evaluation
  #treatment_mode: multiclass
  treatment_mode: multilabel
  autoregressive: True

  treatment_list:
    - cfnlf
    #- wspd
    #- skt
  outcome_list:
    - prate
  vital_list:
    - pres
    - air
    - dswrf
    - csusf
    - csdlf
    - tmin
  static_list:
    #- lat 无
  drop_first: False                                     # One-hot encoding of categorical static features

exp:
  unscale_rmse: True
  percentage_rmse: False
